import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [description, setDescription] = useState("");
  const [output, setOutput] = useState("");

  async function handleRequest() {
    const JSONData = JSON.stringify({ description: description });

    const response = await fetch("/api/ai_request", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSONData,
    });
    const result = await response.json();

    setOutput(result.data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full">
        <h1>Twitter Bio Generator</h1>
        <div>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleRequest();
            }}>
            <p>
              {
                "Give us a description of yourself, and we'll generate a Twitter bio for you!"
              }
            </p>
            <label>
              Description{" "}
              <input
                type="text"
                onChange={(e) => {
                  setDescription(e.target.value);
                }}
              />
            </label>
            <button>Submit</button>
          </form>
          {output && <div>{output}</div>}
        </div>
      </main>
    </>
  );
}
